//
//  OpenAIDataSource.swift
//  PlantWhisper
//
//  Created by Vikram Singh Depawat on 03/08/26.
//

import Foundation

protocol OpenAIService: Sendable {
    
    /// Sends an image to the AI model and returns structured JSON.
    ///
    /// - Parameters:
    ///   - imageData: JPEG or HEIF image.
    ///   - systemPrompt: System instructions.
    ///   - jsonSchema: JSON schema the model must follow.
    ///
    /// - Returns:
    ///   Raw JSON string generated by the model.
    func generateJSON(
        imageData: Data,
        systemPrompt: String,
        jsonSchema: String
    ) async throws -> String
}
